### PR TITLE
Add Yarn for the project

### PR DESCRIPTION
**Pull request by brenopolanski**
> Yarn is a package fast manager for the code. It's another option for developers to use in place of NPM.

**Reference**: https://yarnpkg.com/en/

### CODE REVIEW

**Comment by setpixel** [comment]
But what's wrong with NPM?

**Comment by brenopolanski** [comment]
Nothing. But developers can install dependencies in two ways, using NPM **or** YARN. :stuck_out_tongue_winking_eye:

**Comment by brenopolanski** [comment]
More about the file `yarn.lock` here: https://yarnpkg.com/lang/en/docs/yarn-lock/

**Comment by setpixel** [comment]
I dont think we are going to add yarn support yet.

**Pull request closed without merging**
