### PR TITLE
Don't overwrite PSD once it is created.

### PR DESCRIPTION
**Pull request by Banbury**
This allows the user to work in Photoshop and use all the features of Photoshop.
The PSD will be generated, if it doesn't exist. After that the PSD will be
reused and changes with Storyboarder's tools will be ignored.
This has the advantage, that information about layers or vector graphics are
retained.
The behaviour can be configured in the Preference dialog.

### CODE REVIEW

**Comment by setpixel** [comment]
Hi @Banbury !!!

Thanks for the PR. But we are planning to implement something similar according to this issue: #481 

What do you think of this solution?

-c

**Comment by Banbury** [comment]
I think my solution is easier (no need to save anything in the metadata) and has the advantage of already existing. Otherwise it does the same as the OP describes. Except for the message box. But I would prefer to protect the slides against editing, when Photoshop is used.

**Comment by audionerd** [comment]
Thanks for the PR. We ended up solving this in a different way.

**Comment by Banbury** [comment]
@audionerd Which way did you solve it?

**Pull request closed without merging**
