### PR TITLE
Shot Generator GTLF Export

### PR DESCRIPTION
**Pull request by VladStepura**
Revisited gltf exporter:
1) Implemented ability to export character pose
2) Fixed attachables export; Attahchables weren't exporting to gltf before
3) Fixed cameras don't export

### CODE REVIEW

**Comment by audionerd** [comment]
If the gLTF export fails, we should notify the user. I’ll add that.

I’m getting an error when attempting GLTF export for the first board in `test/fixtures/example/example.storyboarder`:

```
TypeError: Cannot read property 'toString' of undefined
    at processImage (webpack:///./src/js/vendor/three/examples/js/exporters/GLTFExporter.js?:561:46)
    at processTexture (webpack:///./src/js/vendor/three/examples/js/exporters/GLTFExporter.js?:655:17)
    at processMaterial (webpack:///./src/js/vendor/three/examples/js/exporters/GLTFExporter.js?:731:18)
    at processMesh (webpack:///./src/js/vendor/three/examples/js/exporters/GLTFExporter.js?:1032:24)
    at processNode (webpack:///./src/js/vendor/three/examples/js/exporters/GLTFExporter.js?:1288:20)
    at processScene (webpack:///./src/js/vendor/three/examples/js/exporters/GLTFExporter.js?:1373:22)
    at processInput (webpack:///./src/js/vendor/three/examples/js/exporters/GLTFExporter.js?:1412:11)
    at THREE.GLTFExporter.parse (webpack:///./src/js/vendor/three/examples/js/exporters/GLTFExporter.js?:1431:5)
    at EventEmitter.eval (webpack:///./src/js/hooks/use-export-to-gltf.js?:186:14)
    at EventEmitter.emit (events.js:194:13)
```

**Comment by audionerd** [comment]
I notice the appearance of the actual scene changes once the exporter has run. Should it be manipulating the actual scene?

I added logging to `GLTFExporter.js`. Looks like `processImage` fails on the Ground texture image.

Screen Shot 2020-07-09 at 12 34 14 PM

https://github.com/wonderunit/storyboarder/blob/master/src/js/vendor/three/examples/js/exporters/GLTFExporter.js#L721-L731

**Comment by VladStepura** [comment]
Weird, everything should be copied. It shouldn't affect the actual scene

**Comment by VladStepura** [comment]
Oh, I think I know what might be a problem. When you try to export as gltf scene with room in it, it throws an error. I'm gonna fix that

**Comment by VladStepura** [comment]
The problem should be fixed now

**Comment by audionerd** [comment]
Nice!

Still seeing the scene shift though. Might be an issue with the lights?

Screen Shot 2020-07-09 at 1 27 01 PM

Before Export:
Screen Shot 2020-07-09 at 1 26 04 PM

During/After Export:
Screen Shot 2020-07-09 at 1 26 21 PM

**Comment by VladStepura** [comment]
It seems like a problem with **Spotlight.clone()**. On clone, it clones light's target instead of using an existing one, probably need to treat light differently and set target manually.

**Comment by audionerd** [comment]
How are you testing the exported GLB file? I tried exporting (from example.storyboarder) and importing the GLB into Blender but it's got several problems.

- character IK control points are visible (and way oversized)
- ground texture is not correct, glitchy
- center box from in the scene is the wrong size in the GLTF

**Comment by VladStepura** [comment]
You should use latest version of Blender. In the prev version, they had a lot of problems with gltf import. I'm using Blender 
2.83

**Comment by audionerd** [comment]
Ok, testing in Blender 2.83.2 now. I still see a problem with the ground material though, it’s glitchy.

**Comment by VladStepura** [comment]
Yeah, I see the problem with **glitchy ground** it's again the room object problem. And light problem is also room related. Need to take a closer look at room clone and export

**Comment by VladStepura** [comment]
So I fixed **room light resets** by cloning material manually, cause of array materials don't get cloned. And I fixed **ground flickering** by not exporting ground when room is in the scene. It kinda makes sense that we don't need to export invisible objects

**Comment by audionerd** [comment]
Should Volumes be exported? I don't see them in my test.

**Comment by audionerd** [comment]
Do you have any complex Shot Generator scenes you could test with, and check them in Blender?

Looks pretty good overall, though. I think we could merge it.

**Comment by VladStepura** [comment]
About Volumes, I believe they shouldn't be exported

The only thing that concerns me is an environment model, I'm not sure whatever we should export them or not

**Comment by audionerd** [comment]
glTF export should include the Environment model.

**Comment by VladStepura** [comment]
What do you mean by include? It is already exporting the environment model

**Comment by audionerd** [comment]
Whoops! Sorry, I didn't see those commits! Looks like we’re good to merge.

**Pull request merged**
