### PR TITLE
Adds a way to toggle the story tips on and off

### PR DESCRIPTION
**Pull request by multicoder**
This allows the user to turn off the quotes aka 'StoryTips' in the preferences menu

### CODE REVIEW

**Comment by setpixel** [comment]
Lolz. I did some research on you and I found this picture: 
image

**Comment by multicoder** [comment]
Not sure what you are talking about. Usually a google search for my real name results in a handicapped child, or a mine craft server when my online name is used I used to write a plugin for years ago.

**Comment by multicoder** [comment]
Also,I don't follow politics much... so I have no idea who this is so some kind of link would be probably useful, but not sure what this has to do with me adding a feature to this software.

**Comment by setpixel** [comment]
k cool. you're a troll. you deceptively tried to bundle some bullshit commit. good luck getting your wall built.

**Comment by multicoder** [comment]
Oh your upset over the removal of potitical statements, at least that makes little bit of since. Im fine with updating that code to only be story tips if that is what is desired. However as a best practice you should consider leaving political statements out of software; It is a bad development practice.

**Comment by multicoder** [comment]
After reviewing your messages script in more detail it is now apparent to me your team is only developing this feature to troll others. I now see the large number statements writen in this which are a bad practice. I apologize if the commit i made some how upset you that was simply meant to remove a quote containing current political issues, and instead replace it with a humorous quote from a movie. Reguardless, due to this bad practice improvements to this software can not be shared in good conscious.

**Pull request closed without merging**
