### PR TITLE
Adding shortcuts for leaving text fields

### PR DESCRIPTION
**Pull request by Tilix4**
Frames and Duration :
Blur with Escape and Enter

Action, Dialog and Action :
Blur with Escape and CTRL + Enter

### CODE REVIEW

**Comment by audionerd** [comment]
Added in https://github.com/wonderunit/storyboarder/commit/edadee301b8eae59d496e0363fd6c5565e38b16d

Thanks @Tilix4!

**Comment by eliemichel** [comment]
@audionerd You could have marked the commit edadee3 as being authored by @Tilix4 :/

**Comment by audionerd** [comment]
I credited @Tilix4 in the commit message. Didn't accept the PR directly because it needed a few changes first.

**Comment by Tilix4** [comment]
Hi,
Can you tell us what you changed, what we did wrong ? Because we are working on other things and we want to do it properly.

Thanks !

**Comment by setpixel** [comment]
@Tilix4 would you like to join our slack?

**Comment by Tilix4** [comment]
@setpixel Yes, with pleasure.
Could you add my partner @eliemichel as well ?

**Comment by setpixel** [comment]
sure! whats your emails for the invite?

**Comment by Tilix4** [comment]
Me : felixg.david@gmail.com

Elie : elie@exppad.com

**Comment by audionerd** [comment]
I reformatted for clarity (I tend to follow the 'StandardJS' style, although we don't enforce it) and removed the notification.

**Comment by audionerd** [comment]
Also I skipped the package-lock.json changes, they weren't necessary.

**Comment by audionerd** [comment]
Definitely appreciate the contribution, just needed a few minor tweaks, which most PRs do.

**Pull request closed without merging**
